Repository ponylang/http, pull requests merged in 2022-02, with the labels that each got.

#77 Add nodoc annotation to test code
  http/_test.pony
  http/_test_client.pony
  http/_test_client_error_handling.pony
Labels: discuss during sync

#78 Move PR tests back to be against release
  .github/workflows/pr.yml
Labels: discuss during sync

#79 Support for using ponyup on Windows
  .release-notes/79.md
  make.ps1
Labels: changelog - added, discuss during sync

#80 Update to work with Pony 0.49.0
  .release-notes/49.md
  corral.json
  examples/httpget/httpget.pony
  http/_client_connection.pony
  http/_test.pony
  http/_test_client.pony
  http/_test_client_error_handling.pony
  http/http_client.pony
Labels: changelog - fixed, discuss during sync
