Repository ponylang/http, pull requests merged in 2024-01, with the labels that each got.

#103 Add additional test environments
  .github/workflows/breakage-against-linux-ponyc-latest.yml
  .github/workflows/pr.yml
Labels: discuss during sync

#104 Upgrade OpenSSL 3.x test environment
  .github/workflows/breakage-against-linux-ponyc-latest.yml
  .github/workflows/pr.yml
Labels: discuss during sync

#105 Fix bug triggered by OpenSSL 3.2.0
  .release-notes/openssl3.2.md
  corral.json
  http/_test.pony
  http/test_netssl_105_regression.pony
Labels: changelog - fixed, discuss during sync

#107 Link to the new http_server package for server related development
  http/http.pony
  http/payload.pony
Labels: discuss during sync

#106 Change HTTPClient handler factory creation
  .release-notes/106.md
  examples/httpget/httpget.pony
  http/_test.pony
  http/_test_client.pony
  http/_test_client_error_handling.pony
  http/http_client.pony
  http/test_netssl_105_regression.pony
Labels: do not merge, changelog - changed, discuss during sync
